[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.coverage]
via_ir = true
optimizer = true
optimizer_runs = 200